#!/opt/ast/bin/ksh

################################################################################
#                                                                              #
#                                     is_ly                                    #
#                                                                              #
#                                Is it a leap year?                            #
#                                                                              #
#                            Written by Russell Cannon                         #
#                                                                              #
# A simple program that determines whether the four-digit year it receives as  #
# an argument is a leap year according to the usual rules.                     #
#                                                                              #
# Make this a global function by copying it to a directory defined in the      #
# shell variable FPATH.                                                        #
#                                                                              #
################################################################################

# Function: get_ly
#
# A one-liner that returns a 1 if the parameter is a leap yers and a 0 if not.
# First, take a modulo 100.
#  If true, take a modulo of 400.
#   If true, it IS a leap year so print 1.
#   Else, it IS NOT a leap year, so print 0.
#  If modulo 100 is false, modulo by 4.
#   If true, it IS a leap year.
#   Else, it is NOT a leap year.

function get_ly {
 (($1%100==0)) && {(($1%400==0)) && print 1 || print 0;} || {(($1%4==0)) && print 1 || print 0;}
}

