#!/usr/bin/env ksh

################################################################################
#                                                                              #
#                                     is_ly                                    #
#                                                                              #
#                                Is it a leap year?                            #
#                                                                              #
#                            Written by Russell Cannon                         #
#                                                                              #
# A simple program that determines whether the four-digit year it receives as  #
# an argument is a leap year according to the usual rules.                     #
#                                                                              #
# Make this a global function by copying it to a directory defined in the      #
# shell variable FPATH.                                                        #
#                                                                              #
################################################################################

# Function: is_ly
#
# A one-liner that returns a 1 if the parameter is a leap year and a 0 if not.
# First, modulo the parameter with 100.
#  If zero, modulo with 400.
#   If zero, it IS a leap year, so print 1.
#   Else, it IS NOT a leap year, so print 0.
#  If modulo 100 is non-zero, modulo with 4.
#   If zero, it IS a leap year.  Print 1.
#   Else, it is NOT a leap year.  Print 0.

function is_ly {
 (($1%100==0)) && {(($1%400==0)) && print 1 || print 0;} || {(($1%4==0)) && print 1 || print 0;}
}

# Note:  This was originally done with a slightly longer function that used
# proper if/then/else constructs which as more readable, but once I had that
# algorithm down, I instinctively knew that it could be done with a one-liner.
# The syntax was fiddly, but it worked out.

# This file is part of my public domain github repository that can be found here:
#
# https://github.com/RussCannon/ksh-scripts
